name: "wb_embedder_v0"
platform: "ensemble"
max_batch_size: 256
input [
  {
    name: "INPUT_TEXT"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]
output [
  {
    name: "OUTPUT"
    data_type: TYPE_FP32
    dims: [ 1024 ]
  }
]
ensemble_scheduling {
  step [
    {
      model_name: "multilingual-e5-large-preprocessing"
      model_version: -1
      input_map {
        key: "text"
        value: "INPUT_TEXT" # input of ensemble
      }
      output_map {
        key: "output_attention_mask"
        value: "OUTPUT_ATTENTION_MASK"
      }
      output_map {
        key: "output_input_ids"
        value: "OUTPUT_INPUT_IDS"
      }
    },
    {
      model_name: "multilingual-e5-large-onnx"
      model_version: 1
      input_map {
        key: "attention_mask"
        value: "OUTPUT_ATTENTION_MASK"
      }
      input_map {
        key: "input_ids"
        value: "OUTPUT_INPUT_IDS"
      }
      output_map {
        key: "sentence_embedding"
        value: "OUTPUT_EMBEDDING"
      }
    },
    {
      model_name: "multilingual-e5-large-postprocessing"
      model_version: -1
      input_map {
        key: "input_vector"
        value: "OUTPUT_EMBEDDING"
      }
      output_map {
        key: "output_vector"
        value: "OUTPUT"
      }
    }
  ]
}