name: "multilingual-e5-large-postprocessing"
backend: "python"
max_batch_size: 256
input [
{
    name: "input_vector"
    data_type: TYPE_FP32
    dims: [ 1024 ]
}
]

output [
{
    name: "output_vector"
    data_type: TYPE_FP32
    dims: [ 1024 ]
}
]
instance_group [
    {
      count: 10
      kind: KIND_CPU
    }
]

